# HI机器人部署配置
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/hi/policy_lstm_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/hi/scene.xml"

# 总仿真时间
simulation_duration: 60.0
# 仿真时间步长
simulation_dt: 0.002
# 控制器更新频率 (满足 simulation_dt * control_decimation=0.02; 50Hz)
control_decimation: 10

# HI机器人的PD控制参数 (基于hi_config.py中的stiffness和damping配置)
################ original ################
# kps: [25, 25, 25, 30, 8, 8, 25, 25, 25, 30, 8, 8]
# kds: [2.5, 2.5, 2.5, 3.0, 1.5, 1.5, 2.5, 2.5, 2.5, 3.0, 1.5, 1.5]
################ test 20000 ################
# kps: [40, 35, 30, 50, 12, 10, 40, 35, 30, 50, 12, 10]
# kds: [6.0, 5.0, 4.0, 8.0, 2.5, 2.0, 6.0, 5.0, 4.0, 8.0, 2.5, 2.0]
################ test newkds 10000 ################
kps: [40, 40, 30, 35, 20, 15, 40, 40, 30, 35, 20, 15]
kds: [6.0, 6.0, 5.0, 6.0, 4.0, 3.5, 6.0, 6.0, 5.0, 6.0, 4.0, 3.5]
# 默认关节角度 (基于hi_config.py中的default_joint_angles)
default_angles: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0, 
                 -0.1, 0.0, 0.0, 0.3, -0.2, 0.0]

# 观测值缩放参数
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

# 初始命令
cmd_init: [0.0, 0, 0]
